### ISSUE TITLE
Async Read And Write

### ISSUE THREAD

**Issue by beckend** [ChanTsune/Portable-Network-Archive#410]
Requesting API to async read and write.

**Comment by ChanTsune** [comment]
Hi @beckend !

Thank you for your interest in PNA!

I have released experimental async read/write API in `libpna` version `0.6.2`. The async API is available by enabling the `unstable-async` feature.
Examples of the async API can be found in #420

Any feedback is welcome!

**Comment by beckend** [comment]
Thank you!
